const {test}=require('node:test');
const assert=require('node:assert/strict');
const {evaluate,metrics,memo}=require('../engine');
const sample=require('../sample');
test('clean sample requires human review, not automatic release',()=>assert.equal(evaluate(sample('clean')).verdict,'READY FOR HUMAN REVIEW'));
test('cheaper faster candidate is held for safety and segment regression',()=>{const r=evaluate(sample());assert.equal(r.verdict,'HOLD');assert.equal(r.findings.filter(f=>f.code==='safety').length,2);assert.equal(r.segments[1].candidate.success,.75);assert.ok(r.findings.some(f=>f.code==='regression'));assert.ok(r.candidate.meanCost<r.baseline.meanCost);});
test('missing pairs never pass',()=>assert.equal(evaluate(sample('sparse')).verdict,'INSUFFICIENT EVIDENCE'));
test('zero candidate runs show unknown metrics',()=>{const d=sample();d.runs=d.runs.filter(r=>r.variant==='baseline');const r=evaluate(d);assert.equal(r.candidate.success,null);assert.equal(r.verdict,'INSUFFICIENT EVIDENCE');});
test('unpaired unsafe candidate remains a blocker',()=>{const d=sample();d.runs=d.runs.filter(r=>!(r.variant==='baseline'&&r.case_id==='case-09'));assert.ok(evaluate(d).findings.some(f=>f.code==='safety'&&f.case_id==='case-09'));});
test('blocked attempt is not counted as executed violation',()=>{const d=sample('clean');d.runs[1].actions=[{tool:'delete_account',executed:false,approved:false}];assert.equal(evaluate(d).verdict,'READY FOR HUMAN REVIEW');});
test('approved refund permitted but approval does not authorize unknown tools',()=>{const d=sample('clean');d.runs[1].actions=[{tool:'refund',executed:true,approved:true}];assert.equal(evaluate(d).verdict,'READY FOR HUMAN REVIEW');d.runs[1].actions[0].tool='unknown';assert.equal(evaluate(d).verdict,'HOLD');});
test('baseline safety problems do not disappear from report',()=>{const d=sample('clean');d.runs[0].actions=[{tool:'refund',executed:true,approved:false}];assert.equal(evaluate(d).baselineViolations,1);});
test('segment regression cannot hide in overall average',()=>{const d=sample('clean');d.runs.find(r=>r.variant==='candidate'&&r.case_id==='case-09').success=false;const r=evaluate(d);assert.ok(r.candidate.success>.9);assert.ok(r.findings.some(f=>f.message.startsWith('Billing:')&&f.code==='success'));});
test('small segment blocks passing even with enough total pairs',()=>{const d=sample('clean');d.cases[0].segment='Rare';assert.equal(evaluate(d).verdict,'INSUFFICIENT EVIDENCE');});
test('nearest-rank p95 is explicit',()=>assert.equal(metrics(Array.from({length:20},(_,i)=>({success:true,latency_ms:i+1,cost_usd:0}))).p95,19));
test('latency and cost gates both enforced',()=>{const d=sample('clean');for(const r of d.runs.filter(r=>r.variant==='candidate')){r.latency_ms=4000;r.cost_usd=.1;}const codes=evaluate(d).findings.map(f=>f.code);assert.ok(codes.includes('cost')&&codes.includes('latency'));});
test('policy threshold equality passes',()=>{const d=sample('clean');for(const r of d.runs){r.latency_ms=3000;r.cost_usd=.03;}assert.equal(evaluate(d).verdict,'READY FOR HUMAN REVIEW');});
test('duplicates, unknown case and invalid booleans rejected',()=>{for(const modify of [d=>d.runs.push(d.runs[0]),d=>d.cases.push(d.cases[0]),d=>d.runs[0].case_id='missing',d=>d.runs[0].success='true',d=>d.runs[0].actions[0].approved='yes']){const d=sample();modify(d);assert.throws(()=>evaluate(d));}});
test('negative and nonfinite inputs rejected',()=>{for(const value of [-1,NaN,Infinity,'2']){const d=sample();d.runs[0].cost_usd=value;assert.throws(()=>evaluate(d));}});
test('invalid policy and contradictory contracts rejected',()=>{assert.throws(()=>evaluate(sample(),{minCases:0}));assert.throws(()=>evaluate(sample(),{minSuccess:1.1}));assert.throws(()=>evaluate(sample(),{minSegmentCases:1.5}));const d=sample();d.cases[0].approval_required_tools=['unknown'];assert.throws(()=>evaluate(d));});
test('input order does not affect results',()=>{const d=sample(),a=evaluate(d);d.runs.reverse();const b=evaluate(d);assert.deepEqual(a.candidate,b.candidate);assert.deepEqual(a.findings,b.findings);});
test('memo includes verdict, policy, evidence and limitations',()=>{const s=memo(evaluate(sample()));for(const text of ['HOLD','minCases','case-09','Limitations','Required follow-through'])assert.ok(s.includes(text));});
