// Optional real-browser smoke test. Uses an isolated temporary data directory.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const data = fs.mkdtempSync(path.join(os.tmpdir(), 'sentinel-browser-'));
let server, browser;
async function main() {
  server = spawn(process.env.PYTHON || 'python3', ['app.py', '--port', '0', '--data-dir', data, '--interval', '60'], { cwd: root });
  const url = await new Promise((resolve, reject) => {
    let out = '';
    server.stdout.on('data', b => { out += b; const m = out.match(/http:\/\/127\.0\.0\.1:\d+/); if (m) resolve(m[0]); });
    server.once('error', reject);
    server.once('exit', code => reject(Error('Server exited before startup: ' + code)));
  });
  const options = { headless: true };
  if (process.env.BROWSER_EXECUTABLE) Object.assign(options, { executablePath: process.env.BROWSER_EXECUTABLE, args: ['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu'] });
  browser = await chromium.launch(options);
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  page.setDefaultTimeout(10000);
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(url);
  await page.locator('#projectName').filter({ hasText: 'Atlas Partner API' }).waitFor();
  assert.equal(await page.locator('#health').innerText(), 'Needs attention');
  assert.equal(await page.locator('#alerts article').count(), 13);
  fs.mkdirSync(path.join(root, 'assets'), { recursive: true });
  await page.screenshot({ path: path.join(root, 'assets/dashboard.jpg'), type: 'jpeg', quality: 82 });
  console.log('PASS desktop load and risk assessment');
  await page.getByRole('button', { name: 'Acknowledge', exact: true }).first().click();
  await page.locator('#toast').filter({ hasText: 'Acknowledged.' }).waitFor();
  await page.selectOption('#alertFilter', 'acknowledged');
  assert.equal(await page.locator('#alerts article').count(), 1);
  await page.selectOption('#alertFilter', 'active');
  console.log('PASS acknowledge and filter');
  await page.getByRole('button', { name: 'Edit Authentication contract', exact: true }).click();
  await page.selectOption('#editStatus', 'done');
  assert.equal(await page.inputValue('#editProgress'), '100');
  await page.getByRole('button', { name: 'Save and recheck project', exact: true }).click();
  await page.locator('#taskDialog').waitFor({ state: 'hidden' });
  assert.ok((await page.locator('#taskRows tr').filter({ hasText: 'Authentication contract' }).innerText()).includes('done'));
  console.log('PASS task completion and refreshed assessment');
  await page.click('#statusBtn');
  await page.fill('#statusCritical', '0'); await page.fill('#statusHigh', '0'); await page.fill('#statusFailed', '0');
  await page.selectOption('.decision-state', 'decided');
  await page.getByRole('button', { name: 'Save evidence and recheck', exact: true }).click();
  await page.locator('#statusDialog').waitFor({ state: 'hidden' });
  await page.selectOption('#alertFilter', 'resolved');
  assert.ok((await page.locator('#alerts').innerText()).includes('Quality needs a release decision'));
  console.log('PASS evidence update and resolved alerts');
  await page.selectOption('#alertFilter', 'active');
  await page.getByRole('button', { name: /Pulse Analytics Refresh/ }).click();
  assert.equal(await page.locator('#health').innerText(), 'On track');
  console.log('PASS project switch and healthy state');
  await page.click('#createBtn');
  await page.fill('#newName', 'Northstar Demo'); await page.fill('#newOwner', 'Test PM'); await page.fill('#newObjective', 'Validate a product delivery workflow');
  await page.fill('.base-title', 'Build prototype'); await page.fill('.base-owner', 'Jess'); await page.fill('.base-points', '10');
  await page.getByRole('button', { name: 'Create project and begin monitoring', exact: true }).click();
  await page.locator('#createDialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('#projectName').innerText(), 'Northstar Demo');
  console.log('PASS create project without JSON');
  await page.click('#addTaskBtn'); await page.fill('#scopeTitle', 'Additional reporting'); await page.fill('#scopePoints', '5');
  await page.getByRole('button', { name: 'Add work and assess impact', exact: true }).click();
  await page.locator('#scopeDialog').waitFor({ state: 'hidden' });
  assert.ok((await page.locator('#alerts').innerText()).includes('Scope changed after kickoff'));
  console.log('PASS scope addition and baseline drift');
  let downloadPromise = page.waitForEvent('download'); await page.click('#exportBtn');
  let download = await downloadPromise; const project = JSON.parse(fs.readFileSync(await download.path(), 'utf8'));
  assert.equal(project.baseline.scope_points, 10); assert.equal(project.tasks.length, 2);
  downloadPromise = page.waitForEvent('download'); await page.click('#reportBtn'); download = await downloadPromise;
  assert.ok(fs.readFileSync(await download.path(), 'utf8').includes('Northstar Demo'));
  console.log('PASS JSON and PM brief downloads');
  await page.click('#importBtn'); project.baseline.budget += 1;
  await page.fill('#importText', JSON.stringify(project)); await page.click('#confirmImport');
  await page.locator('#importError').filter({ hasText: 'Baseline is locked' }).waitFor();
  await page.keyboard.press('Escape');
  console.log('PASS invalid baseline import rejected in UI');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(root, 'assets/mobile-check.jpg'), type: 'jpeg', quality: 75, fullPage: true });
  const overflow = await page.evaluate(() => [...document.querySelectorAll('body *')].filter(n => n.getBoundingClientRect().right > innerWidth + 1 && getComputedStyle(n).position !== 'fixed').map(n=>({tag:n.tagName,id:n.id,class:n.className,right:Math.round(n.getBoundingClientRect().right)})).slice(0,25));
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)) console.log('Overflow details:', overflow);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.screenshot({ path: path.join(data, 'mobile.png'), fullPage: true });
  await page.locator('#createBtn').focus(); await page.keyboard.press('Tab');
  assert.equal(await page.locator('#importBtn').evaluate(n => n === document.activeElement), true);
  assert.deepEqual(errors, []);
  console.log('PASS mobile overflow, keyboard focus, and no JavaScript page errors');
  console.log('10 browser workflow checks passed.');
}
main().catch(e => { console.error(e); process.exitCode = 1; }).finally(async () => {
  if (browser) await browser.close();
  if (server && server.exitCode === null) { const exited = new Promise(resolve => server.once('exit', resolve)); server.kill(); await exited; }
  fs.rmSync(data, { recursive: true, force: true });
});
